
export const arry1 =  [
    { id:"1", firstName:"Great", lastName:"Ibe"},
    { id:"2", firstName:"John", lastName:"Wolf"},
    { id:"3", firstName:"Esther", lastName:"Algo"},
    { id:"4", firstName:"Elizabeth", lastName:"Duro"},
    { id:"5", firstName:"Greg", lastName:"Otos"},
    { id:"6", firstName:"Junior", lastName:"Ajakaye"},
    { id:"7", firstName:"Kefe", lastName:"Luther"},
    { id:"8", firstName:"Peace", lastName:"Udenzie"},
    { id:"9", firstName:"Nathan", lastName:"Rhona"},
    { id:"10", firstName:"Duro", lastName:"Lekan"},
    { id:"11", firstName:"David", lastName:"Orunor"},
    { id:"12", firstName:"Ana", lastName:"Flourish"},
    { id:"13", firstName:"Demo", lastName:"Favour"},
    { id:"14", firstName:"Annabella", lastName:"Revival"},
    { id:"15", firstName:"Ezotech", lastName:"Mute"},
    { id:"16", firstName:"Sammy", lastName:"Omu"},
    { id:"17", firstName:"Alex", lastName:"Dangote"},
    { id:"18", firstName:"Tricia", lastName:"Emmanuel"},
    { id:"19", firstName:"Samuel", lastName:"Lemuel"},
    { id:"20", firstName:"Peter", lastName:"Kingsley"},
    { id:"21", firstName:"Prince", lastName:"Nicholas"},
    { id:"22", firstName:"Joseph", lastName:"Magdalene"},
    { id:"23", firstName:"Tega", lastName:"Wealth"},
    { id:"24", firstName:"Elijah", lastName:"Fola"},
    { id:"25", firstName:"Elisha", lastName:"Trust"},
    { id:"26", firstName:"Anastasia", lastName:"Zino"},
    { id:"27", firstName:"Zemoora", lastName:"Christabel"},
  ]